server:
  port: 80

country: China

user1:
  name: frank
  age: 12

users:
  - name: frank
    age: 21
  - name: lily
    age: 22

baseDir: C:\Users\11195

# use "" to make it transfer th meaning
tmpDir: ${baseDir}\IdeaProjects

data1:
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost/springboot.db
  username: root
  password: 123456

